const skills = [
    { id: "Python", name: "Python" },
    { id: "JavaScript", name: "JavaScript" },
    { id: "Java", name: "Java" },
    { id: "C#", name: "C#" },
    { id: "C++", name: "C++" },
    { id: "Ruby", name: "Ruby" },
    { id: "Swift", name: "Swift" },
    { id: "Kotlin", name: "Kotlin" },
    { id: "TypeScript", name: "TypeScript" },
    { id: "Go", name: "Go" },
    { id: "Rust", name: "Rust" },
    { id: "PHP", name: "PHP" },
    { id: "HTML", name: "HTML" },
    { id: "CSS", name: "CSS" },
    { id: "SQL", name: "SQL" },
    { id: "Bash", name: "Bash" },
    { id: "PowerShell", name: "PowerShell" },
    { id: "Frontend development", name: "Frontend development" },
    { id: "Backend development", name: "Backend development" },
    { id: "Full-stack development", name: "Full-stack development" },
    { id: "Responsive web design", name: "Responsive web design" },
    { id: "Web performance optimization", name: "Web performance optimization" },
    { id: "Web security", name: "Web security" },
    { id: "React Native", name: "React Native" },
    { id: "Flutter", name: "Flutter" },
    { id: "Amazon Web Services (AWS)", name: "Amazon Web Services (AWS)" },
    { id: "Microsoft Azure", name: "Microsoft Azure" },
    { id: "Google Cloud Platform (GCP)", name: "Google Cloud Platform (GCP)" },
    { id: "Cloud architecture", name: "Cloud architecture" },
    { id: "Cloud security", name: "Cloud security" },
    { id: "Serverless computing", name: "Serverless computing" },
    { id: "Continuous Integration/Continuous Deployment (CI/CD)", name: "Continuous Integration/Continuous Deployment (CI/CD)" },
    { id: "Infrastructure as Code (IaC)", name: "Infrastructure as Code (IaC)" },
    { id: "Docker", name: "Docker" },
    { id: "Kubernetes", name: "Kubernetes" },
    { id: "Ansible", name: "Ansible" },
    { id: "Puppet", name: "Puppet" },
    { id: "Chef", name: "Chef" },
    { id: "MySQL", name: "MySQL" },
    { id: "PostgreSQL", name: "PostgreSQL" },
    { id: "SQL Server", name: "SQL Server" },
    { id: "Oracle", name: "Oracle" },
    { id: "MongoDB", name: "MongoDB" },
    { id: "Cassandra", name: "Cassandra" },
    { id: "Redis", name: "Redis" },
    { id: "Database design and optimization", name: "Database design and optimization" },
    { id: "Data warehousing", name: "Data warehousing" },
    { id: "Network security", name: "Network security" },
    { id: "Web security", name: "Web security" },
    { id: "Ethical hacking", name: "Ethical hacking" },
    { id: "Incident response", name: "Incident response" },
    { id: "Cryptography", name: "Cryptography" },
    { id: "GDPR warehousing", name: "GDPR warehousing" },
    { id: "HIPAA", name: "HIPAA" },
    { id: "PCI DSS", name: "PCI DSS" },
    { id: "Machine learning algorithms", name: "Machine learning algorithms" },
    { id: "TensorFlow", name: "TensorFlow" },
    { id: "PyTorch", name: "PyTorch" },
    { id: "Natural Language Processing (NLP)", name: "Natural Language Processing (NLP)" },
    { id: "Computer Vision", name: "Computer Vision" },
    { id: "Reinforcement Learning", name: "Reinforcement Learning" },
    { id: "AI ethics and bias", name: "AI ethics and bias" },
    { id: "Tableau", name: "Tableau" },
    { id: "Power BI", name: "Power BI" },
    { id: "matplotlib", name: "matplotlib" },
    { id: "seaborn", name: "seaborn" },
    { id: "Statistical analysis", name: "Statistical analysis" },
    { id: "Data mining", name: "Data mining" },
    { id: "Hadoop", name: "Hadoop" },
    { id: "Spark", name: "Spark" },
    { id: "Predictive modeling", name: "Predictive modeling" },
    { id: "Data storytelling", name: "Data storytelling" },
    { id: "TCP/IP networking", name: "TCP/IP networking" },
    { id: "Routing and switching", name: "Routing and switching" },
    { id: "Network security", name: "Network security" },
    { id: "Software-defined networking (SDN)", name: "Software-defined networking (SDN)" },
    { id: "Wireless networking", name: "Wireless networking" },
    { id: "Windows", name: "Windows" },
    { id: "Linux (Ubuntu, CentOS, Red Hat)", name: "Linux (Ubuntu, CentOS, Red Hat)" },
    { id: "macOS", name: "macOS" },
    { id: "Unix", name: "Unix" },
    { id: "Agile", name: "Agile" },
    { id: "Scrum", name: "Scrum" },
    { id: "Kanban", name: "Kanban" },
    { id: "Waterfall", name: "Waterfall" },
    { id: "Git", name: "Git" },
    { id: "SVN", name: "SVN" },
    { id: "Mercurial", name: "Mercurial" },
    { id: "Project planning and scheduling", name: "Project planning and scheduling" },
    { id: "Risk management", name: "Risk management" },
    { id: "Stakeholder communication", name: "Stakeholder communication" },
    { id: "Resource management", name: "Resource management" },
    { id: "ITIL(Information Technology Infrastructure Library)", name: "ITIL(Information Technology Infrastructure Library)" },
    { id: "Incident management", name: "Incident management" },
    { id: "Change management", name: "Change management" },
    { id: "Service desk management", name: "Service desk management" },
    { id: "React.js", name: "React.js" },
    { id: "Angular", name: "Angular" },
    { id: "Vue.js", name: "Vue.js" },
    { id: "jQuery", name: "jQuery" },
    { id: "Bootstrap", name: "Bootstrap" },
    { id: "Tailwind CSS", name: "Tailwind CSS" },
];
export default skills;











